### ISSUE TITLE
[PE-D][Tester D] Table of contents in UG is not working

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-W13-1/tp#121]
There is a table of content heading, but it seems that the link is broken or the table is not being displayed.

![image.png](https://raw.githubusercontent.com/quannam0124/ped/main/files/f9067ae5-1c6f-4992-bba9-912dab9d32ff.png)

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: quannam0124/ped#6

**Comment by lpohsien** [comment]
#166
