### ISSUE TITLE
[PE-D][Tester E] Weak phone number input validation

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-W13-1/tp#126]
There is a lack of phone number validation, enabling me to input a very large number, which was accepted as a valid phone number.

Could possibly use stricter regex to fix this problem! Although the input format should probably vary depending on the localisation of the app (could specify for Singapore numbers first)

![image.png](https://raw.githubusercontent.com/riccqi/ped/main/files/c0bb9778-8eaa-43a9-ae55-b454815ee366.png)

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: riccqi/ped#4

**Comment by comicalromance** [comment]
Might also not really be a bug tbh, some phone numbers can be quite long
