### ISSUE TITLE
[PE-D][Tester A] Formatting errors with command summary

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-W13-1/tp#128]
![image.png](https://raw.githubusercontent.com/charleslimjh/ped/main/files/11af55e0-3fd5-4799-8436-748d4fcae782.png)

Table headers for the command summary are not formatted properly.

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: charleslimjh/ped#2

**Comment by comicalromance** [comment]
duplicate of #153
