### ISSUE TITLE
[PE-D][Tester C] Sort phone number with very huge phone number

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-W13-1/tp#156]
With someone have a huge phone number but sorted in ascending order, it is placed before others with a number smaller than it

![Screenshot (91).png](https://raw.githubusercontent.com/maxng17/ped/main/files/d96c05e3-bda3-42f7-88d3-417b94508a24.png)

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: maxng17/ped#13

**Comment by lpohsien** [comment]
I don't really think this is a bug though. Phone numbers should behave more like strings than integers (one is more likely to recall the first few digits of the phone number and search for it that way instead of length of the number). Maybe we just need to specify it more clearly in the user guide.

**Comment by comicalromance** [comment]
agree with po-hsien
